self-hosted-runner:
  labels:
    - self-hosted
    - linux
    - amd64
    - tiobe
    - noble

paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # TODO: Remove this once actionlint supports GitHub's self-repository ($/) syntax.
      - 'reusable workflow call "\$/\.github/workflows/.+" at "uses" is not following the format'
