rules:
  dependabot-cooldown:
    config:
      days: 3

  # Allowlist trusted actions and pre-commit repos.
  forbidden-uses:
    config:
      allow:
        - canonical/*
        - actions/*
        - pypa/gh-action-pypi-publish
        - tiobe/tics-github-action
        - python-poetry/poetry
        - pre-commit/pre-commit-hooks
        - astral-sh/ruff-pre-commit
        - codespell-project/codespell
        - rhysd/actionlint
  unpinned-uses:
    config:
      policies:
        canonical/*: ref-pin
        actions/*: ref-pin
        pypa/gh-action-pypi-publish: ref-pin
        tiobe/tics-github-action: ref-pin
  secrets-inherit:
    ignore:
      - ci.yaml:178
  # Since actionlint don't support $/.. syntax
  self-repository:
    disable: true
