default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
  - post-checkout
  - post-merge

default_stages:
  - pre-commit

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply

  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.1
    hooks:
      - id: poetry-check
        args: [--no-cache]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-toml
      - id: detect-private-key
        exclude: ^tests/integration/ha/test_backup.py
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: ^opensearch_single_kernel/lib/
        exclude_types:
          - svg
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      exclude: ^opensearch_single_kernel/lib/

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    - id: isort
      exclude: ^opensearch_single_kernel/lib/

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      exclude: ^opensearch_single_kernel/lib/
      additional_dependencies:
        - Flake8-pyproject
        - flake8-copyright
        - flake8-docstrings
        - pep8-naming




  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      additional_dependencies: [tomli]
      args: ["--write-changes"]
      exclude: ^poetry\.lock$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
    - id: actionlint

exclude: |
  (?x)(
    ^docs/.*
  )
