# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
env_list = lint, unit

[vars]
src_path = {tox_root}/opensearch-single-kernel
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
set_env =
    PY_COLORS = 1
allowlist_externals =
    poetry

[testenv:format]
description = Apply coding style standards to code
commands_pre =
    poetry install --only format
commands =
    poetry lock
    poetry run ruff check  --config pyproject.toml --fix {[vars]all_path}
    poetry run ruff format --config pyproject.toml {[vars]all_path}

[testenv:build]
description = Builds the package
commands_pre =
    poetry install
commands =
    poetry lock
    poetry build


[testenv:lint]
description = Check code against coding style standards
allowlist_externals =
    {[testenv]allowlist_externals}
    find
commands_pre =
    poetry install --only lint
commands =
    poetry check --lock
    poetry run codespell --toml {tox_root}/pyproject.toml {[vars]all_path}
    poetry run ruff check --config {tox_root}/pyproject.toml {[vars]all_path}
    poetry run ruff format --check --config {tox_root}/pyproject.toml --diff {[vars]all_path}
    find {[vars]all_path} -type f \( -name "*.sh" -o -name "*.bash" \) -exec poetry run shellcheck --color=always \{\} +

# Backward compatibility with default unit env
[testenv:unit]
description = Run unit tests
set_env =
    {[testenv]set_env}
commands_pre =
    poetry install --only main,charm-libs,unit
commands =
    poetry run coverage run --source={[vars]src_path} \
    -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit
    poetry run coverage report
    poetry run coverage xml

[testenv:unit-lxd]
description = Run unit tests
set_env =
    {[testenv]set_env}
commands_pre =
    poetry install --only main,charm-libs,unit
commands =
    poetry run coverage run --source={[vars]src_path} \
    -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit --substrate lxd
    poetry run coverage report
    poetry run coverage xml

[testenv:unit-microk8s]
description = Run unit tests
set_env =
    {[testenv]set_env}
commands_pre =
    poetry install --only main,charm-libs,unit
commands =
    poetry run coverage run --source={[vars]src_path} \
    -m pytest -v --tb native -s {posargs} {[vars]tests_path}/unit --substrate microk8s
    poetry run coverage report
    poetry run coverage xml

[testenv:integration]
description = Run integration tests
pass_env =
    CI
    AWS_ACCESS_KEY
    AWS_SECRET_KEY
    GCP_ACCESS_KEY
    GCP_SECRET_KEY
commands_pre =
    poetry install --only integration
commands =
    poetry run pytest -v --tb native --log-cli-level=INFO -s --ignore={[vars]tests_path}/unit/ {posargs}
