#!/usr/bin/env python3
# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

"""OpenSearch Cluster manager."""

import logging
import time
from datetime import datetime

from shortuuid import ShortUUID
from tenacity import (
    Retrying,
    stop_after_attempt,
    wait_exponential,
)

from opensearch_single_kernel.common.constants import (
    PEER_CLUSTER_NO_RELATION,
    PEER_CLUSTER_WRONG_RELATION,
    CertType,
    DeploymentType,
    Directive,
    Scope,
    StartMode,
    State,
)
from opensearch_single_kernel.common.exceptions import (
    OpenSearchCmdError,
    OpenSearchHttpError,
    OpenSearchNotFullyReadyError,
    OpenSearchStartTimeoutError,
)
from opensearch_single_kernel.core.models import (
    App,
    DeploymentDescription,
    DeploymentState,
    Node,
    PeerClusterConfig,
)
from opensearch_single_kernel.core.state import ClusterState
from opensearch_single_kernel.managers.base import BaseManager
from opensearch_single_kernel.utils.config import YamlConfigSetter
from opensearch_single_kernel.utils.helpers import deployment_type
from opensearch_single_kernel.utils.topology import ClusterTopology
from opensearch_single_kernel.workload.base import BaseWorkload

logger = logging.getLogger(__name__)


class ClusterManager(BaseManager):
    """OpenSearch Cluster Manager.

    This manager is responsible for the different operations regarding configuring and
    managing opensearch cluster.
    """

    CONFIG_YML = "opensearch.yml"

    def __init__(self, state: ClusterState, workload: BaseWorkload):
        super().__init__(state, workload)
        self.name = "cluster_manager"
        self.yaml_setter = YamlConfigSetter(self.workload.paths.conf)

    def start(self, wait_until_http_200: bool = True):
        """Start the opensearch service."""

        def _is_connected():
            return self.is_node_up() if wait_until_http_200 else self.is_opensearch_started

        if self.is_opensearch_started:
            return

        # start the opensearch service
        self.workload.start_service()

        start = datetime.now()
        while not (connected := _is_connected()) and (datetime.now() - start).seconds < 180:
            time.sleep(3)
        if not connected:
            logger.debug(f"waited {datetime.now() - start} opensearch did not start")
            raise OpenSearchStartTimeoutError()

    def reconcile_peer_cluster_config(self) -> None:
        """Init, or updates / recomputes current peer cluster related config if applies."""
        logger.debug("Running peer cluster manager reconcile function")
        user_config = self._user_config()
        if not (self.state.application.deployment_desc):
            # new cluster
            deployment_desc = self._new_cluster_setup(user_config)
            logger.debug("New deployment_desc from new cluster setup: %s", deployment_desc)
            self.state.application.put_object("deployment-description", deployment_desc.to_dict())
            return

        # TODO: Handle existing cluster case

    def _new_cluster_setup(self, config: PeerClusterConfig) -> DeploymentDescription:
        """Build deployment description of a new cluster."""
        logger.debug("New cluster setup")
        directives = []
        deployment_state = DeploymentState(value=State.ACTIVE)
        if config.init_hold:
            # checks if peer cluster relation is set
            if not self.state.peer_cluster_relation:
                deployment_state = DeploymentState(
                    value=State.BLOCKED_WAITING_FOR_RELATION, message=PEER_CLUSTER_NO_RELATION
                )
                directives.append(Directive.SHOW_STATUS)
                directives.append(Directive.WAIT_FOR_PEER_CLUSTER_RELATION)

            directives.append(
                Directive.VALIDATE_CLUSTER_NAME
                if config.cluster_name
                else Directive.INHERIT_CLUSTER_NAME
            )

            start_mode = (
                StartMode.WITH_PROVIDED_ROLES if config.roles else StartMode.WITH_GENERATED_ROLES
            )
            return DeploymentDescription(
                app=App(model_uuid=self.state.model_uuid, name=self.state.application.name),
                config=config,
                start=start_mode,
                pending_directives=directives,
                typ=deployment_type(config, start_mode),
                state=deployment_state,
            )

        cluster_name_autogenerated = False
        if not (cluster_name := config.cluster_name.strip()):
            cluster_name = f"{self.state.application.name}-{ShortUUID().random(length=4)}".lower()
            cluster_name_autogenerated = True

        if not config.roles:
            start_mode = StartMode.WITH_GENERATED_ROLES
        else:
            start_mode = StartMode.WITH_PROVIDED_ROLES
            if "cluster_manager" not in config.roles:
                deployment_state = DeploymentState(
                    value=State.BLOCKED_CANNOT_START_WITH_ROLES,
                    message=PEER_CLUSTER_WRONG_RELATION,
                )
                directives.append(Directive.WAIT_FOR_PEER_CLUSTER_RELATION)
                directives.append(Directive.SHOW_STATUS)

        return DeploymentDescription(
            app=App(model_uuid=self.state.model_uuid, name=self.state.application.name),
            config=PeerClusterConfig(
                cluster_name=cluster_name,
                init_hold=config.init_hold,
                roles=config.roles,
                data_temperature=config.data_temperature,
            ),
            start=start_mode,
            pending_directives=directives,
            typ=deployment_type(config, start_mode),
            state=deployment_state,
            cluster_name_autogenerated=cluster_name_autogenerated,
        )

    def _user_config(self):
        """Build a user provided config object."""
        return PeerClusterConfig(
            cluster_name=self.state.config.get("cluster_name"),
            init_hold=self.state.config.get("init_hold", False),
            roles=[
                option.strip().lower()
                for option in self.state.config.get("roles", "").split(",")
                if option
            ],
        )

    def cleanup_bootstrap_conf(self):
        """Clean up bootstrap state and remove initial_cluster_manager_nodes from config"""
        if self.state.server.is_app_leader:
            self.state.application.update({"bootstrapped": "True"})
        self.state.server.update({"bootstrap_contributor": None})

    def should_initialise_security_index(self) -> bool:
        """Returns whether the unit should initialise the security index."""
        return (
            self.state.server.is_app_leader
            and not self.state.application.security_index_initialised
            and (
                "data" in self.state.application.deployment_desc.config.roles
                or self.state.application.deployment_desc.start == StartMode.WITH_GENERATED_ROLES
            )
        )

    def initialise_security_index(self):
        """Initialise security Index.

        This function is called after opensearch has started.

        Run the security_admin script, it creates and initializes the opendistro_security index.

        IMPORTANT: must only run once per cluster, otherwise the index gets overrode
        """
        admin_secrets = self.state.secrets.get_object(Scope.APP, CertType.APP_ADMIN.val, peek=True)
        try:
            args = [
                f"-cd {self.workload.paths.conf}/opensearch-security/",
                f"-cn {self.state.application.deployment_desc.config.cluster_name}",
                f"-h {self.state.host_ip}",
                # f"-ts {self.workload.paths.certs}/ca.p12",
                # f"-tspass {self.state.secrets.get_object(Scope.APP,
                # CertType.APP_ADMIN.val, peek=True)['truststore-password']}",
                # "-tsalias ca",
                # "-tst PKCS12",
                # f"-ks {self.workload.paths.certs}/{CertType.APP_ADMIN}.p12",
                # f"-kspass {self.state.secrets.get_object(Scope.APP,
                #  CertType.APP_ADMIN.val, peek=True)['keystore-password']}",
                # f"-ksalias {CertType.APP_ADMIN}",
                # "-kst PKCS12",
            ]

            admin_key_pwd = admin_secrets.get("key-password", None)
            if admin_key_pwd is not None:
                args.append(f"-keypass {admin_key_pwd}")

            self.workload.run_script(
                "plugins/opensearch-security/tools/securityadmin.sh", " ".join(args)
            )
            self._put_security_index_initialised()

        except OpenSearchCmdError as e:
            logger.debug(f"Error when initializing the security index: {e.out}")
            raise e

    def apply_peer_cm_directives_and_check_if_can_start(self) -> bool:
        """Apply the directives computed by the opensearch peer cluster manager."""
        if not (deployment_desc := self.state.application.deployment_desc):
            # the deployment description hasn't finished being computed by the leader
            return False

        # check possibility to start
        logger.debug("Checking if cluster can start with deploy desc: %s", deployment_desc)
        if self.can_start(deployment_desc):
            try:
                self.get_nodes(False)
            except OpenSearchHttpError:
                return False
            return True
        return False

    def _put_security_index_initialised(self):
        """Set the security index initialized flag."""
        # TODO: Add peer cluster updates here we need to update relations
        self.state.application.update({"security_index_initialised": "True"})

    def wait_for_opensearch_up(self):
        """Wait for opensearch to be fully ready."""
        # it sometimes takes a few seconds before the node is fully "up" otherwise a 503 error
        # may be thrown when calling a node - we want to ensure this node is perfectly ready
        # before marking it as ready
        for attempt in Retrying(
            stop=stop_after_attempt(5),
            wait=wait_exponential(multiplier=2, min=2, max=10),
            reraise=True,
        ):
            with attempt:
                if not self.is_node_up():
                    raise OpenSearchNotFullyReadyError("Node started but not fully ready yet.")

    def can_start(self, deployment_desc: DeploymentDescription | None = None) -> bool:
        """Return whether the service of a node can start."""
        if not (deployment_desc := deployment_desc or self.state.application.deployment_desc):
            return False

        blocking_directives = [
            Directive.WAIT_FOR_PEER_CLUSTER_RELATION,
            Directive.RECONFIGURE,
            Directive.VALIDATE_CLUSTER_NAME,
            Directive.INHERIT_CLUSTER_NAME,
        ]
        logger.debug("Directives: %s", deployment_desc.pending_directives)
        for directive in deployment_desc.pending_directives:
            if directive in blocking_directives:
                logger.debug("blocking directive %s", directive)
                return False

        return True

    def get_nodes(self, use_localhost: bool) -> list[Node]:
        """Fetch the list of nodes of the cluster, depending on the requester."""
        if self.state.planned_units == 0 and not self.state.application.deployment_desc:
            # This app is going away and the -broken event already happened
            return []

        # This means it's the first unit on the cluster.
        if self.state.application.deployment_desc.start == StartMode.WITH_PROVIDED_ROLES:
            computed_roles = self.state.application.deployment_desc.config.roles
        else:
            computed_roles = ClusterTopology.generated_roles()

        if (
            self.state.server.is_app_leader
            and "data" in computed_roles
            and not self.state.application.security_index_initialised
        ):
            return []
        return ClusterTopology.nodes(self.opensearch_client, use_localhost, self.alt_hosts)

    def clear_directive(self, directive: Directive):
        """Remove directive after having applied it."""
        if not (deployment_desc := self.state.application.deployment_desc):
            return

        if directive not in deployment_desc.pending_directives:
            return

        deployment_desc.pending_directives.remove(directive)
        logger.debug("Clearing directive %s. DeploymentDesc: %s", directive, deployment_desc)
        self.state.application.put_object("deployment-description", deployment_desc.to_dict())

    def compute_and_broadcast_updated_topology(self, current_nodes: list[Node]) -> bool:
        """Compute cluster topology and broadcast node configs (roles for now) to change if any.

        Returns whether a nodes_config object has been updated or not.
        """
        if not current_nodes:
            return False

        current_reported_nodes = {
            name: Node.from_dict(node)
            for name, node in (self.state.application.nodes_config or {}).items()
        }

        if (
            deployment_desc := self.state.application.deployment_desc
        ).start == StartMode.WITH_GENERATED_ROLES:
            updated_nodes = ClusterTopology.recompute_nodes_conf(
                app_id=deployment_desc.app.id, nodes=current_nodes
            )
        else:
            updated_nodes = {}
            for node in current_nodes:
                roles = node.roles
                temperature = node.temperature

                # only change the roles of the nodes of the current cluster
                if node.app.id == deployment_desc.app.id:
                    roles = deployment_desc.config.roles
                    temperature = deployment_desc.config.data_temperature

                updated_nodes[node.name] = Node(
                    name=node.name,
                    roles=roles,
                    ip=node.ip,
                    app=node.app,
                    unit_number=self.state.server.unit_id,
                    temperature=temperature,
                )

        if current_reported_nodes == updated_nodes:
            return False

        self.state.application.put_object("nodes_config", updated_nodes)
        return True

    def clean_up_started_state(self) -> None:
        """Remove the 'started' key from the unit state."""
        self.state.server.relation_data.pop("started")

    def is_node_up(self):
        """Check whether opensearch is up"""
        return self.opensearch_client.is_node_up()

    def _is_failover_and_sole_data_app(self) -> bool:
        """Check if the current node is a failover and the only data node in the cluster."""
        deployment_desc = self.state.application.deployment_desc
        cluster_fleet_apps = self.state.application.cluster_fleet_apps or {}
        return (
            # data node in a failover orchestrator deployment
            deployment_desc.typ == DeploymentType.FAILOVER_ORCHESTRATOR
            and (
                "data" in deployment_desc.config.roles
                or deployment_desc.start == StartMode.WITH_GENERATED_ROLES
            )
            # No pure data nodes in the cluster
            and not any(
                self.state.application.name != cluster_fleet_apps[app].get("app", {}).get("name")
                and "data" in cluster_fleet_apps[app].get("roles", [])
                and "cluster_manager" not in cluster_fleet_apps[app].get("roles", [])
                for app in cluster_fleet_apps
            )
        )

    def configure_bootstrap_contributors(
        self,
        computed_roles: list[str],
        cm_names: list[str],
        cm_ips: list[str],
    ) -> bool:
        """Configure application state with bootstrap contributors.

        This function takes the computed rolesn cluster managers names and ips,
        it configure the application state and return whether the current unit contribute
        to bootstrap.
        """
        contribute_to_bootstrap = False
        if "cluster_manager" in computed_roles:
            cm_names.append(self.state.unit_name)
            cm_ips.append(self.state.host_ip)

            if (
                self.state.application.deployment_desc.typ == DeploymentType.MAIN_ORCHESTRATOR
                and not self.state.application.bootstrapped
            ):
                cms_in_bootstrap = self.state.application.bootstrap_contributors_count
                if cms_in_bootstrap < self.state.planned_units:
                    contribute_to_bootstrap = True

                    if self.state.server.is_app_leader:
                        self.state.application.bootstrap_contributors_count = cms_in_bootstrap + 1

                    # indicates that this unit is part of the "initial cm nodes"
                    self.state.server.bootstrap_contributor = True
        return contribute_to_bootstrap

    def computed_roles(self):
        """Return computed_roles"""
        if (
            deployment_desc := self.state.application.deployment_desc
        ).start == StartMode.WITH_PROVIDED_ROLES:
            computed_roles = deployment_desc.config.roles
        else:
            computed_roles = ClusterTopology.generated_roles()

        # If the failover orchestrator is the only data node in the cluster, remove the
        # cluster-manager role from it to avoid it bootstrapping the cluster
        # which is the responsibility of the main orchestrator
        # who then broadcasts `security_index_initialized` to the peer clusters.
        if (
            self.state.server.is_app_leader
            and self._is_failover_and_sole_data_app()
            and not self.state.application.security_index_initialised
        ):
            self.state.server.cluster_manager_removed = True
            computed_roles.remove("cluster_manager")

        if computed_roles == ["coordinating"]:
            computed_roles = []  # to mark a node as dedicated coordinating only, we clear the list
        return computed_roles

    @property
    def is_opensearch_started(self) -> bool:
        """Returns whether OpenSearch has started."""
        reachable = self.workload.is_reachable(self.state.host_ip, self.state.port)
        if not reachable:
            logger.debug("Cannot connect to the OpenSearch server...")

        return reachable

    @property
    def roles(self) -> list[str]:
        """Get the list of the roles assigned to this node."""
        try:
            return self.opensearch_client.get_roles(self.state.unit_name, self.state.alt_hosts)
        except OpenSearchHttpError:
            return self.yaml_setter.load("opensearch.yml")["node.roles"]
