#!/usr/bin/env python3
# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

import logging
import time

import jubilant
import pytest
from data_platform_helpers.advanced_statuses import StatusObject

from opensearch_single_kernel.common.statuses import (
    PeerClusterErrorDataStatuses,
    PeerClusterStatuses,
    TlsStatuses,
)
from tests.integration.conftest import CONFIG_OPTS, MODEL_CONFIG
from tests.integration.ha.continuous_writes import ContinuousWrites
from tests.integration.ha.helpers import all_nodes
from tests.integration.ha.test_horizontal_scaling import IDLE_PERIOD
from tests.integration.helpers import (
    _series_to_base,
    get_leader_unit_ip,
    wait_until,
)
from tests.integration.tls.test_tls import TLS_CERTIFICATES_APP_NAME, TLS_STABLE_CHANNEL

logger = logging.getLogger(__name__)

REL_ORCHESTRATOR = "peer-cluster-orchestrator"
REL_PEER = "peer-cluster"

MAIN_APP_NOT_AUTOGEN = "opensearch-main"
INVALID_FAILOVER_APP = "opensearch-failover-invalid"

MAIN_APP_AUTOGEN = "opensearch-main-autogen"
FAILOVER_APP_AUTOGEN = "opensearch-failover-autogen"
DATA_APP_AUTOGEN = "opensearch-data-autogen"

CLUSTER_NAME = "log-app"

NON_AUTOGEN_APP_UNITS = {
    MAIN_APP_NOT_AUTOGEN: 1,
    INVALID_FAILOVER_APP: 1,
}

AUTOGEN_APP_UNITS = {
    MAIN_APP_AUTOGEN: 1,
    FAILOVER_APP_AUTOGEN: 1,
    DATA_APP_AUTOGEN: 2,
}

NO_DATA_NODE_STATUS_MESSAGE = "Missing requirements: At least 1 data nodes are required."
NO_CM_STATUS_MESSAGE = "Missing requirements: At least 1 cluster manager nodes are required."


NO_DATA_NODE_STATUS = StatusObject(
    status="blocked",
    message="Missing requirements: At least 1 data nodes are required.",
)
NO_CM_STATUS = StatusObject(
    status="blocked",
    message="Missing requirements: At least 1 cluster manager nodes are required.",
)


@pytest.mark.group(id="Cluster name not autogenerated")
@pytest.mark.abort_on_fail
@pytest.mark.skip_if_deployed
async def test_build_and_deploy_not_autogen(juju: jubilant.Juju, charm, series) -> None:
    """Build and deploy one unit of OpenSearch without autogenerated cluster name."""
    # it is possible for users to provide their own cluster for HA testing.
    # Hence, check if there is a pre-existing cluster.
    juju.model_config(MODEL_CONFIG)

    # Deploy TLS Certificates operator.
    config = {"ca-common-name": "CN_CA"}
    juju.deploy(TLS_CERTIFICATES_APP_NAME, channel=TLS_STABLE_CHANNEL, config=config)
    juju.deploy(
        charm,
        app=MAIN_APP_NOT_AUTOGEN,
        num_units=1,
        base=_series_to_base(series),
        config={"cluster_name": CLUSTER_NAME} | CONFIG_OPTS,
    )
    juju.deploy(
        charm,
        app=INVALID_FAILOVER_APP,
        num_units=1,
        base=_series_to_base(series),
        config={"init_hold": True, "roles": "cluster_manager"} | CONFIG_OPTS,
    )

    # wait until the TLS operator is ready
    await wait_until(
        juju,
        apps=[TLS_CERTIFICATES_APP_NAME],
        wait_for_exact_units={TLS_CERTIFICATES_APP_NAME: 1},
        idle_period=IDLE_PERIOD,
    )

    # integrate TLS to all applications
    for app in [
        MAIN_APP_NOT_AUTOGEN,
        INVALID_FAILOVER_APP,
    ]:
        juju.integrate(app, TLS_CERTIFICATES_APP_NAME)

    # confirm all apps are blocked due to missing data node or waiting for relation
    await wait_until(
        juju,
        apps=list(NON_AUTOGEN_APP_UNITS.keys()),
        apps_statuses={
            INVALID_FAILOVER_APP: [PeerClusterStatuses.PEER_CLUSTER_NO_RELATION.value],
        },
        units_statuses={
            INVALID_FAILOVER_APP: [NO_DATA_NODE_STATUS],
        },
        wait_for_exact_units={app: units for app, units in NON_AUTOGEN_APP_UNITS.items()},
        idle_period=IDLE_PERIOD,
        timeout=1800,
    )


@pytest.mark.group(id="Cluster name autogenerated")
@pytest.mark.abort_on_fail
@pytest.mark.skip_if_deployed
async def test_build_and_deploy_autogen(juju: jubilant.Juju, charm, series) -> None:
    """Build and deploy one unit of OpenSearch with autogenerated cluster name."""
    # it is possible for users to provide their own cluster for HA testing.
    # Hence, check if there is a pre-existing cluster.
    juju.model_config(MODEL_CONFIG)

    # Deploy TLS Certificates operator.
    config = {"ca-common-name": "CN_CA"}
    juju.deploy(TLS_CERTIFICATES_APP_NAME, channel=TLS_STABLE_CHANNEL, config=config)
    juju.deploy(
        charm,
        app=MAIN_APP_AUTOGEN,
        num_units=1,
        base=_series_to_base(series),
        config={"roles": "cluster_manager"} | CONFIG_OPTS,
    )
    juju.deploy(
        charm,
        app=FAILOVER_APP_AUTOGEN,
        num_units=1,
        base=_series_to_base(series),
        config={"init_hold": True, "roles": "cluster_manager"} | CONFIG_OPTS,
    )
    juju.deploy(
        charm,
        app=DATA_APP_AUTOGEN,
        num_units=2,
        base=_series_to_base(series),
        config={"init_hold": True, "roles": "data"} | CONFIG_OPTS,
    )

    # wait until the TLS operator is ready
    await wait_until(
        juju,
        apps=[TLS_CERTIFICATES_APP_NAME],
        wait_for_exact_units={TLS_CERTIFICATES_APP_NAME: 1},
        idle_period=IDLE_PERIOD,
        timeout=1800,
    )

    # integrate TLS to all applications
    for app in [
        MAIN_APP_AUTOGEN,
        FAILOVER_APP_AUTOGEN,
        DATA_APP_AUTOGEN,
    ]:
        juju.integrate(app, TLS_CERTIFICATES_APP_NAME)

    # confirm all apps are blocked due to missing data node or waiting for relation
    await wait_until(
        juju,
        apps=list(AUTOGEN_APP_UNITS.keys()),
        apps_statuses={
            MAIN_APP_AUTOGEN: [
                NO_DATA_NODE_STATUS,
                PeerClusterStatuses.PEER_CLUSTER_NO_DATA_NODE.value,
            ],
            FAILOVER_APP_AUTOGEN: [PeerClusterStatuses.PEER_CLUSTER_NO_RELATION.value],
            DATA_APP_AUTOGEN: [PeerClusterStatuses.PEER_CLUSTER_NO_RELATION.value],
        },
        units_statuses={
            MAIN_APP_AUTOGEN: [
                NO_DATA_NODE_STATUS,
                PeerClusterStatuses.PEER_CLUSTER_NO_DATA_NODE.value,
            ],
            FAILOVER_APP_AUTOGEN: [NO_DATA_NODE_STATUS],
            DATA_APP_AUTOGEN: [NO_CM_STATUS],
        },
        wait_for_exact_units={app: units for app, units in AUTOGEN_APP_UNITS.items()},
        idle_period=IDLE_PERIOD,
    )


@pytest.mark.group(id="Cluster name not autogenerated")
@pytest.mark.abort_on_fail
async def test_invalid_inherit_cluster_name_integration(juju: jubilant.Juju) -> None:
    """If the cluster name wasn't auto generated, cluster name should not be inherited"""
    juju.integrate(
        f"{INVALID_FAILOVER_APP}:{REL_PEER}",
        f"{MAIN_APP_NOT_AUTOGEN}:{REL_ORCHESTRATOR}",
    )

    await wait_until(
        juju,
        apps=[MAIN_APP_NOT_AUTOGEN, INVALID_FAILOVER_APP],
        apps_statuses={
            INVALID_FAILOVER_APP: [
                PeerClusterErrorDataStatuses.CANNOT_RELATE_TO_CLUSTER_WITH_DIFFERENT_NAME.value,
            ],
        },
        units_statuses={
            INVALID_FAILOVER_APP: [
                TlsStatuses.TLS_NOT_FULLY_CONFIGURED.value,
            ],
        },
        wait_for_exact_units={app: units for app, units in NON_AUTOGEN_APP_UNITS.items()},
        idle_period=IDLE_PERIOD,
    )


@pytest.mark.group(id="Cluster name autogenerated")
@pytest.mark.abort_on_fail
async def test_cluster_name_inheritence_and_integration(juju: jubilant.Juju) -> None:
    """Data and failover apps should inherit cluster name and integrate with cluster manager."""
    juju.integrate(f"{DATA_APP_AUTOGEN}:{REL_PEER}", f"{MAIN_APP_AUTOGEN}:{REL_ORCHESTRATOR}")

    await wait_until(
        juju,
        apps=[MAIN_APP_AUTOGEN, DATA_APP_AUTOGEN],
        wait_for_exact_units={
            app: AUTOGEN_APP_UNITS[app] for app in [MAIN_APP_AUTOGEN, DATA_APP_AUTOGEN]
        },
        idle_period=IDLE_PERIOD,
    )

    juju.integrate(f"{FAILOVER_APP_AUTOGEN}:{REL_PEER}", f"{MAIN_APP_AUTOGEN}:{REL_ORCHESTRATOR}")
    juju.integrate(f"{DATA_APP_AUTOGEN}:{REL_PEER}", f"{FAILOVER_APP_AUTOGEN}:{REL_ORCHESTRATOR}")

    await wait_until(
        juju,
        apps=[MAIN_APP_AUTOGEN, DATA_APP_AUTOGEN, FAILOVER_APP_AUTOGEN],
        wait_for_exact_units={
            app: AUTOGEN_APP_UNITS[app]
            for app in [MAIN_APP_AUTOGEN, DATA_APP_AUTOGEN, FAILOVER_APP_AUTOGEN]
        },
        idle_period=IDLE_PERIOD,
    )

    # make sure data can be written
    c_writes = ContinuousWrites(juju, app=DATA_APP_AUTOGEN)
    await c_writes.start()
    time.sleep(30)
    await c_writes.stop()
    assert (await c_writes.count()) > 0, "Continuous writes did not increase"

    leader_unit_ip = await get_leader_unit_ip(juju, app=MAIN_APP_AUTOGEN)
    nodes = await all_nodes(juju, leader_unit_ip, app=MAIN_APP_AUTOGEN)
    assert len(nodes) == 4, f"Wrong node count. Expecting 4 online nodes, found: {len(nodes)}."
