name: Linting, and Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  workflow_dispatch:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true
      AWS_ACCESS_KEY:
        required: true
      AWS_SECRET_KEY:
        required: true
      AZURE_STORAGE_ACCOUNT:
        required: true
      AZURE_SECRET_KEY:
        required: true
      GCP_ACCESS_KEY:
        required: true
      GCP_SECRET_KEY:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true

permissions:
  contents: read

jobs:
  pre-commit:
    name: Run pre-commits
    runs-on: ubuntu-latest
    if: false # Disabled for now
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tox, poetry & pre-commit
        run: |
          pipx install tox poetry pre-commit
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install pre-commit hooks
        run: pre-commit install
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

  actionlint:
    name: Lint .github/workflows/
    if: false # Disabled for now
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v50.0.0

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    if: false # Disabled for now
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.7.0
        continue-on-error: true
        with:
          charm-path: ./opensearch_single_kernel/
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: write

  tox-lint:
    name: tox run -e lint
    runs-on: ubuntu-latest
    if: false # Disabled for now
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox poetry
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Run linters
        run: tox run -e lint

  unit-test:
    name: Unit test charm
    if: false # Disabled for now
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tox & poetry
        run: |
          pipx install tox poetry
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Run tests
        run: tox run -e unit

  build:
    name: Build test charms
    runs-on: ubuntu-latest
    if: false # Disabled for now
    timeout-minutes: 120
    strategy:
      matrix:
        path:
          - tests/charms/opensearch_test_charm
          - tests/charms/opensearch_k8s_test_charm
          - tests/charms/opensearch_k8s_2.19.4_test_charm
          - tests/charms/dummy-client-charm
          - tests/integration/relations/opensearch_provider/application-charm
    steps:
      - name: Install CLI
        run: pipx install git+https://github.com/canonical/data-platform-workflows@v50.0.0#subdirectory=_cli
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install tox & poetry
        shell: bash
        run: |
          pipx install tox poetry
          pipx inject poetry poetry-plugin-export
      - name: Set up environment
        run: |
          sudo snap install lxd
          # shellcheck disable=SC2078
          # (shellcheck sees it as constant, but GitHub Actions expression is not constant between workflow runs)
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sudo --user` instead
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT

          # Remove this once this is fixed: https://github.com/canonical/charmcraft/issues/2620
          sudo snap install charmcraft --classic --revision=7517
          pipx install charmcraftcache
      - name: Set up python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Update lib and build charm
        shell: bash
        run: |
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- bash scripts/build_lib_for_integration.sh ${{ matrix.path }}
        env:
          CI_CACHE: false
      - name: Compute path in artifact
        id: path-in-artifact
        run: compute-path-in-artifact '${{ matrix.path }}'
      - name: Upload charm
        uses: actions/upload-artifact@v4
        with:
          name: packed-charm-${{ steps.path-in-artifact.outputs.path }}
          path: |
            ${{ matrix.path }}/*.charm
            .empty
          if-no-files-found: error

  integration-test:
    name: Integration test charm
    needs:
      - build
    uses: ./.github/workflows/integration_test.yaml
    with:
      artifact-prefix: packed-charm
      run-on-all-bases: ${{ github.event_name == 'schedule' }}
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_SECRET_KEY: ${{ secrets.AZURE_SECRET_KEY }}
      GCP_ACCESS_KEY: ${{ secrets.GCP_ACCESS_KEY }}
      GCP_SECRET_KEY: ${{ secrets.GCP_SECRET_KEY }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
    permissions:
      contents: write # Needed for Allure Report
