# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to PyPI

on:
  push:
    branches:
      - 2/edge
      - feature/single-kernel

concurrency:
  # Prevent race conditions (if multiple commits have been pushed since the last release)
  group: dpw-release-python-package-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  release-part1:
    needs:
      - ci
    name: Release to PyPI (part 1)
    uses: canonical/data-platform-workflows/.github/workflows/release_python_package_part1.yaml@v31.1.1
    permissions:
      contents: write  # Needed to create git tag

  # Separate job needed to workaround https://github.com/pypi/warehouse/issues/11096
  release-trusted-publishing:
    name: Release to PyPI (trusted publishing)
    needs:
      - release-part1
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # Change environment name if we are on test feature
    environment: ${{ github.ref_name == 'feature/single-kernel' && 'testpypi' || 'production' }}
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.release-part1.outputs.artifact-name }}
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Configure repository url, by default it is pypi.
          repository_url: ${{ github.ref_name == 'feature/single-kernel' && 'https://test.pypi.org/legacy/' || 'https://upload.pypi.org/legacy/' }}
    permissions:
      id-token: write  # Needed for PyPI trusted publishing

  release-part2:
    name: Release to PyPI (part 2)
    needs:
      - release-part1
      - release-trusted-publishing
    uses: canonical/data-platform-workflows/.github/workflows/release_python_package_part2.yaml@v31.1.1
    with:
      git-tag: ${{ needs.release-part1.outputs.git-tag }}
    permissions:
      contents: write  # Needed to create GitHub release
